(defun split-kv (line)
  (let ((pos (position #\= line)))
    (unless pos (error "invalid vector line: ~A" line))
    (values (subseq line 0 pos) (subseq line (1+ pos)))))

(defun load-vector (path)
  (let ((table (make-hash-table :test #'equal)))
    (with-open-file (stream path :direction :input)
      (loop for line = (read-line stream nil nil)
            while line
            unless (string= line "")
              do (multiple-value-bind (key value) (split-kv line)
                   (setf (gethash key table) value))))
    table))

(let* ((args sb-ext:*posix-argv*)
       (path (car (last args)))
       (v (load-vector path))
       (verified (gethash "verification_label" v))
       (evidence (gethash "evidence" v))
       (source (gethash "source" v))
       (backtrace (or (and (string= verified "PRESENT")
                           (not (string= evidence "PRESENT")))
                      (string= source "UNKNOWN")))
       (verdict (if backtrace "BACKTRACE" "ACCEPT"))
       (operator (if backtrace "GLT-0036" "NONE"))
       (state (if backtrace "CONTESTED" "ACCEPTED")))
  (format t "~A|~A|~A|~A|~A~%"
          (gethash "vector_id" v)
          (gethash "protocol_version" v)
          verdict operator state))
