export const CMB_INVARIANTS = Object.freeze({
  PATTERN_NOT_PROOF: "PATTERN != PROOF",
  PROFILE_NOT_PERSON: "PROFILE != PERSON",
  MODEL_NOT_MIND: "MODEL != MIND",
  PREDICTION_NOT_DESTINY: "PREDICTION != DESTINY",
  CAPABILITY_NOT_AUTHORITY: "CAPABILITY != AUTHORITY",
  HUMAN_AGENCY_OVER_MACHINE_AUTHORITY: "HUMAN_AGENCY > MACHINE_AUTHORITY",
} as const);

export type CmbInvariant =
  (typeof CMB_INVARIANTS)[keyof typeof CMB_INVARIANTS];
